pipelines:
  default:
    - step:
        script:
          - echo "Nothing to do.... push successfullllllll.... :)"
  branches:
    master:
      - step:
          image: samueldebruyn/debian-git
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp.mwhost.ga/public_html